// Use "side effect" imports. They install custom elements in the registry
import './StackLayout.js'
import './BoxLayout.js'
import './CenterLayout.js'
import './ClusterLayout.js'
import './SidebarLayout.js'
import './SwitcherLayout.js'
import './CoverLayout.js'
import './GridLayout.js'
import './FrameLayout.js'
import './ReelLayout.js'
